---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: couchdb.database.svc.cluster.local
  DB_NAME: items_db
  DB_PORT: "5984"
  KAFKA_BROKER: my-kafka.kafka.svc.cluster.local:9092
  KAFKA_ENABLED: "true"
  KAFKA_GROUP_ID: test-consumer-group
  KAFKA_TOPIC: items-topic
  REDIS_DB: "5"
  REDIS_HOST: redis.database.svc.cluster.local
  REDIS_PORT: "6379"