---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-backend
  name: api-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-backend
  template:
    metadata:
      labels:
        app: api-backend
    spec:
      containers:
      - image: ghcr.io/xamma/msdemo-backend:latest
        name: msdemo-backend
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
