---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-svc
  name: backend-svc
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: api-backend
  type: ClusterIP
